export enum CategoriaEnum {
    Todos = 0,
	PolosYCamisetasHombre = 1,
	Camisas = 2,
	Pantalones = 3,
	Shorts = 4,
	AbrigosYCasacasHombre = 5,
	RopaDeportivaHombre = 6,
	BlusasYCamisas = 7,
	Vestidos = 8,
	PantalonesYFaldas = 9,
	AbrigosYCasacasMujer = 10,
	RopaDeportivaMujer = 11,
	PolosYCamisetasNinos = 12,
	PantalonesYShortsNinos = 13,
	VestidosYFaldasNinos = 14,
	AbrigosYCasacasNinos = 15,
	RopaDeportivaNinos = 16,
}
